#!/bin/bash

show-help() {
	echo -e "\nDelete all posts -p [post type]"
	echo -e "\tExample: ddev wp-cleanup -p shop_order,product"
	echo -e "\nDelete all logs -l [wp-content path]"
	echo -e "\tExample: ddev wp-cleanup -l uploads/wc-logs\n"
	echo -e "\nReset the DB to a fresh installation"
  echo -e "\tExample: ddev wp-cleanup -r\n"
}

delete-posts() {
	for post in $(wp post list --post_type=$1 --format=ids --path=.ddev/wordpress); do
		wp post delete $post --force --path=.ddev/wordpress
	done
}

delete-logs() {
	rm .ddev/wordpress/wp-content/$1/*.log
}

reset-db() {
  wp db reset --yes --path=.ddev/wordpress
  wp core install \
    --path=.ddev/wordpress \
    --url=wp-test-site.ddev.site \
    --title="Testing Cart" \
    --admin_user=admin \
    --admin_password=5hwnZU#aQxCK#Ld#voUIteU6 \
    --admin_email=test@ddev.site
}

declare -i param_counter=0

while getopts "p:l:h:r" arg; do
	case $arg in
	p)
		delete-posts $OPTARG
		param_counter+=1
		;;
	l)
		delete-logs $OPTARG
		param_counter+=1
		;;
  r)
    reset-db
    param_counter+=1
    ;;
	h) show-help ;;
	esac
done

if [ $param_counter -eq 0 ]; then
	show-help
fi
