services:
  web:
    volumes:
      - ../wp-featureflags:/var/www/html/.ddev/wordpress/wp-content/plugins/wp-featureflags:ro
      - ../wp-featureflags/config:/var/www/html/.ddev/wordpress/wp-content/wp-featureflags:ro
